name: Dependabot automerge
description: Automerge pull requests from Dependabot
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: GitHub token to approve the PR with. Defaults to repository token.
    required: false
    default: ${{ github.token }}
  level:
    description: Only approve/merge when the increment is major/minor/patch.
    required: false
    default: minor
